export const SIGN_IN = 'SIGN_IN'
export const SIGN_UP = 'SIGN_UP'
export const LOGOUT = 'LOGOUT'

export const SET_GUEST = "SET_GUEST"
export const UPDATE_GUEST = "UPDATE_GUEST"
export const SIGN_OUT_GUEST = "SIGN_OUT_GUEST"


export const ADD_TABLET = 'ADD_TABLET'
export const REMOVE_TABLET = 'REMOVE_TABLET'
export const VALID_TABLET = 'VALID_TABLET'
export const MOUNT_TABLETS = 'MOUNT_TABLETS'
export const ACTIVATE = 'ACTIVATE'
export const SET_SOURAS = "SET_SOURAS"
export const SET_SOURA = "SET_SOURA"
export const SET_SOURA_NAME = "SET_SOURA_NAME"
export const SET_TIWAL = "SET_TIWAL"
export const SET_MIIN = "SET_MIIN"
export const SET_MATHANI = "SET_MATHANI"
export const SET_MOFASAL = "SET_MOFASAL"
export const SET_TABLET = "SET_TABLET"
export const SET_CARDS = "SET_CARDS"
export const SET_CARDS_ACCORDION = "SET_CARDS_ACCORDION"
export const SET_AYAHS = "SET_AYAHS"
export const UPDATE_COLUMNS_ORDER = "UPDATE_COLUMNS_ORDER"
export const UPDATE_COLUMN_ITEM_ORDER = "UPDATE_COLUMN_ITEM_ORDER"
export const DELETE_ITEM = "DELETE_ITEM"
export const SET_NMB_TABLET = "SET_NMB_TABLET"
export const SET_TAB = "SET_TAB"
export const SET_WORDS = "SET_WORDS"
export const SET_TABLET_WORDS = "SET_TABLET_WORDS"
export const ADD_CARD_SLICES = "ADD_CARD_SLICES"
export const ADD_AYAT_CARDS = 'ADD_AYAT_CARDS'
export const REMOVE_WORDS = 'REMOVE_WORDS'
export const CLEAR_TABLET_WORDS = 'CLEAR_TABLET_WORDS'



export const ADD_CARD = 'ADD_CARD'
export const REMOVE_CARD = 'REMOVE_CARD'
export const VALID_CARD = 'VALID_CARD'

export const ADD_TO_CART = "ADD_TO_CART"
export const UPDATE_CART = "UPDATE_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const RESET_CART = "RESET_CART"
export const CHECKOUT = "CHECKOUT"
export const NEXT_STEP = "NEXT_STEP"
export const SET_DISCOUNT = "SET_DISCOUNT"
export const HAS_ERROR = "HAS_ERROR"
export const REMOVE_PRODUCT = "REMOVE_PRODUCT"
export const UPDATE_PRODUCT = "UPDATE_PRODUCT"
export const SET_STEP = "SET_STEP"
export const SET_DELIVERY = "SET_DELIVERY"
export const SET_NEXT_STEP = "SET_NEXT_STEP"
export const SET_BACK_STEP = "SET_BACK_STEP"
export const SET_BILLING_ADDRESS = "SET_BILLING_ADDRESS"
export const RESET_BILLING_ADDRESS = "RESET_BILLING_ADDRESS"
export const SET_SHIPPING_CHARGE = "SET_SHIPPING_CHARGE"
export const SET_PAYMENT_METHODE = "SET_PAYMENT_METHODE"
export const SET_PAYMENT_CARD = "SET_PAYMENT_CARD"
export const SET_PAYMENT_TYPE = "SET_PAYMENT_TYPE"
export const RESET_CARD = "RESET_CARD"
export const SET_COMPLETE = "SET_COMPLETE"
export const SET_SUBTOTAL = "SET_SUBTOTAL"
export const SET_TOTAL = "SET_TOTAL"
export const SET_CART_PRODUCTS = "SET_CART_PRODUCTS"
export const SET_TOTAL_QUANTITY = "SET_TOTAL_QUANTITY"
export const SET_OPEN = "SET_OPEN"
export const SET_EDIT = "SET_EDIT"
export const SET_START_DATE = "SET_START_DATE"
export const SET_END_DATE = "SET_END_DATE"


export const SET_PAGE_INDEX = "SET_PAGE_INDEX"
export const SET_PRODUCTS_PENDING = "SET_PRODUCTS_PENDING"
export const SET_PRODUCTS_SUCCESS = "SET_PRODUCTS_SUCCESS"
export const SET_PRODUCTS_FAILURE = "SET_PRODUCTS_FAILURE"
export const SET_SELF_PRODUCTS = "SET_SELF_PRODUCTS"
export const ADD_SELF_PRODUCT = "ADD_SELF_PRODUCT"
export const SET_CONTEXT_PRODUCT = "SET_CONTEXT_PRODUCT"
export const SET_INTERVAL_FILTER = "SET_INTERVAL_FILTER"
export const SET_RELATED_PRODUCTS = "SET_RELATED_PRODUCTS"
export const SET_ALL_PRODUCTS = "SET_ALL_PRODUCTS"
export const SET_PROMOTE = "SET_PROMOTE"
export const SET_SEARCH_RESULT = "SET_SEARCH_RESULT"


export const SET_SELECTIONS_PENDING = "SET_SELECTIONS_PENDING"
export const SET_SELECTIONS_SUCCESS = "SET_SELECTIONS_SUCCESS"
export const SET_SELECTIONS_FAILURE = "SET_SELECTIONS_FAILURE"
export const SET_SELF_SELECTIONS = "SET_SELF_SELECTIONS"
export const ADD_SELF_SELECTION = "ADD_SELF_SELECTION"
export const SET_CONTEXT_SELECTION = "SET_CONTEXT_SELECTION"
export const PROMOTE_SELECTION = "PROMOTE_SELECTION"

export const ADD_COLLABORATOR = "ADD_COLLABORATOR"
export const SET_COLLABORATOR = "SET_COLLABORATOR"
export const SET_COLLABORATOR_AUTH = "SET_COLLABORATOR_AUTH"
export const UPDATE_COLLABORATOR = "UPDATE_COLLABORATOR"
export const SET_COLLABORATOR_NULL = "SET_COLLABORATOR_NULL"



export const ADD_VIEWER = "ADD_VIEWER"
export const SET_VIEWER = "SET_VIEWER"
export const SET_VIEWER_ADDRESS = "SET_VIEWER_ADDRESS"
export const SET_VIEWER_AUTH = "SET_VIEWER_AUTH"
export const UPDATE_VIEWER = "UPDATE_VIEWER"
export const SET_VIEWER_NULL = "SET_VIEWER_NULL"
export const ADD_FOLLOWER = "ADD_FOLLOWER"



// Interface
export const SET_OPEN_MENU = "SET_OPEN_MENU"
